# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the jar file from your local machine to the container
COPY target/todov1-0.0.1-SNAPSHOT.jar app.jar

# Run the Spring Boot application when the container starts
ENTRYPOINT ["java", "-jar", "app.jar"]
